#!/usr/bin/env bash
set -euo pipefail

gdbus call \
  --session \
  --dest org.gnome.Shell \
  --object-path /org/gnome/Shell/Extensions/LightshotLinux \
  --method org.gnome.Shell.Extensions.LightshotLinux.StartCapture >/dev/null
